[package]
authors = ["Pouya M. B. <pooyamb@gmail.com>"]
categories = ["encoding", "web-programming"]
description = "A query string extractor for axum based on serde-querystring"
documentation = "https://docs.rs/serde-querystring-axum"
edition = "2021"
keywords = ["serialization", "deserialization", "querystring", "serde", "axum"]
license = "MIT OR Apache-2.0"
name = "serde-querystring-axum"
readme = "README.md"
repository = "https://github.com/pooyamb/serde-querystring/"
version = "0.3.0"
rust-version = "1.56"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum-core = "0.5.0"
http = "1.5"

serde = { version = "1.0.126", features = ["derive"] }
serde-querystring = { version = "0.3.0", features = ["serde"] }

[dev-dependencies]
axum = "0.8"
http-body-util = "0.1"
tokio = { version = "1.53", features = ["full"] }
tower = "0.5"
